/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import civitas.CivitasJuego;
import controladorCivitas.Respuesta;
import javax.swing.JOptionPane;
import GUI.*;
import civitas.Diario;
import javax.swing.JFrame;

/**
 *
 * @author alexc
 */
public class CivitasView extends javax.swing.JFrame implements Vista{

    private CivitasJuego juego;
                        
    public CivitasView() {
        initComponents();    
        
        setLocationRelativeTo(null);
    }

    public void setJuego(CivitasJuego juego) {
        this.juego = juego;
        this.setVisible(true);
    }
    
    public void actualiza(){
        this.jugadorPanel1.setJugador(juego.getJugadorActual());
        this.casillaPanel.setCasilla(this.juego.getTablero().getCasilla(this.juego.getJugadorCasillaActual()));
        
        this.rankingLabel.setVisible(false);
        this.rankingTextField.setVisible(false);
        
        if(this.juego.finalDelJuego()){
            this.rankingLabel.setVisible(true);
            this.rankingTextField.setVisible(true);
            
            this.rankingTextField.setText(this.juego.ranking()+"");
        }
        
        repaint();
        revalidate();
        
    }
    
    public void mostrarSiguienteOperacion(OperacionJuego operacion){
        this.siguienteOperacionTextField.setText(operacion+"");
        
        if(operacion == OperacionJuego.AVANZAR){
            Dado.createInstance(this);
            Dado d = Dado.getInstance();
            d.tirar(); //Visualizar el tirado del dado
            
            repaint();
        }
    }

    public void pausa(){
        int val = JOptionPane.showConfirmDialog(null, "Continuar?",
                                                        "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if(val == 1){
            System.exit(0);
        }
    }

    public Respuesta comprar(){
        int opcion = JOptionPane.showConfirmDialog(null, "Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        
        return Respuesta.values()[opcion];
    }

    public OperacionInmobiliaria elegirOperacion(){
        GestionarDialog gestion = new GestionarDialog(this, true);
        return OperacionInmobiliaria.values() [gestion.getGestionElegida()];
    }

    public int elegirPropiedad(){
        PropiedadesDialog propieadad = new PropiedadesDialog(this, true, this.juego.getJugadorActual());
        return propieadad.getPropiedadElegida();
    }

    public void mostrarEventos(){
        if(!Diario.getInstance().getEventos().isEmpty()){
            DiarioDialog diarioD = new DiarioDialog(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        jugadorPanel1 = new GUI.JugadorPanel();
        casillaPanel = new GUI.CasillaPanel();
        jLabel1 = new javax.swing.JLabel();
        siguienteOperacionTextField = new javax.swing.JTextField();
        rankingLabel = new javax.swing.JLabel();
        rankingTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloLabel.setText("CivitasJuego");

        jLabel1.setText("Siguiente Operacion:");

        siguienteOperacionTextField.setEditable(false);
        siguienteOperacionTextField.setText("jTextField1");

        rankingLabel.setText("RANKING");

        rankingTextField.setEditable(false);
        rankingTextField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(TituloLabel)
                .addGap(309, 309, 309))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casillaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(rankingLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(siguienteOperacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rankingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rankingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rankingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(siguienteOperacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TituloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** BORAR METODO MAIN
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloLabel;
    private GUI.CasillaPanel casillaPanel;
    private javax.swing.JLabel jLabel1;
    private GUI.JugadorPanel jugadorPanel1;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JTextField rankingTextField;
    private javax.swing.JTextField siguienteOperacionTextField;
    // End of variables declaration//GEN-END:variables
}
